name: CI - Playwright Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Temurin 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: mvn -B -DskipTests install --no-transfer-progress

      - name: Install Playwright browsers
        run: mvn -B exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run DemoQA tests
        run: mvn -B -Dtest=DemoQaTests test --no-transfer-progress || true

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()  # run even if tests failed
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
